### ISSUE TITLE
'thresholdsByMetricIndex' Option Bug

### ISSUE THREAD

**Issue by pd-smith** [commercehub-oss/gatling-gradle-plugin#12]
https://github.com/commercehub-oss/gatling-gradle-plugin/blob/master/src/main/groovy/com/commercehub/gradle/plugin/GatlingTask.groovy#L129

In version 2.1 + , there is a bug related to the 'thresholdsByMetricIndex' option.

The exact nature of the bug requires some investigation, but it's believed to poorly handle:
* not specifying the option at all
* not specifying a threshold for a given index

**Comment by ShawnTurner** [comment]
Can you provide more detail about how to reproduce the issue? The metric thresholds will throw a validation error if they are specified in a way that 's incompatible with any configured metrics. The line linked in this issue points to the koChecker as opposed to any metrics code.

I did move the validation for agreement between thresholds and metrics to earlier in the process, but it was already present.

I will reopen once it can be reproduced.
