### ISSUE TITLE
Is it possible to launch gatling recorder 

### ISSUE THREAD

**Issue by rahulmr** [commercehub-oss/gatling-gradle-plugin#15]
Wanted to know whether it is possible to launch gatling recorder using this plugin.
Thanks

**Comment by ShawnTurner** [comment]
Hi @rahulmr , are you still looking for enhancements to gatling-gradle?

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
