### ISSUE TITLE
Not supported with gradle version 4.2.1

### ISSUE THREAD

**Issue by Manjusha24ct** [commercehub-oss/gatling-gradle-plugin#16]
If used with gradle version 4.2.1 gives an error  
"Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0"

**Comment by ShawnTurner** [comment]
Support for newer versions of Gradle is currently being developed as a solution to this issue.
