### ISSUE TITLE
Metrics to Check Restructure

### ISSUE THREAD

**Issue by pd-smith** [commercehub-oss/gatling-gradle-plugin#9]
Currently our metric configurations look like:

```
metrics {
        metricsToCheck = ['some:metric', 'another:metric']
        daysToCheck = 5
        degradationTolerance = 0.50
}
```

Meaning we can only check for the same degradation tolerance and time frame for all metrics in a given test. 
Perhaps restructuring to:

```
metrics {
        "some:metric": {
            daysToCheck = 5
            degradationTolerance = 0.50
        }
        "another:metric": {
            daysToCheck = 10
            degradationTolerance = 0.25
        }
 }
```

would give us more flexibility.

**Comment by ShawnTurner** [comment]
Configuration per metric sounds like a good enhancement to me.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
